version: "3"

services:
  db:
    container_name: assistant_db
    build:
      context: ./db
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    volumes:
      - ./db/sql_script:/sql_script

  gateway:
    container_name: assistant_gateway
    build:
      context: ./gateway
    ports:
      - 80:80
    expose:
      - '80'
    restart: always
    volumes:
      - ./gateway/conf/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - user
      - recommend
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

  user:
    container_name: assistant_user
    build:
      context: ./user
    ports:
      - 8001:8001
    environment:
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_NAME: ${DB_NAME}"
      DB_HOST: 'db'
    volumes:
      - ./user/app:/app
    command: '/bin/sh -c "npm install && npm start"'
  
  recommend:
    container_name: assistant_recommend
    build:
      context: ./recommend
    ports:
      - 8002:8002
    environment:
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_NAME: ${DB_NAME}"
      DB_HOST: 'db'
    volumes:
      - ./user/app:/app
    command: '/bin/sh -c "npm install && npm start"'
